#pragma checksum "Views\WindowTyp2.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "85CC72210D9DA58C0A378D35F47627E01D79B73B32AEDB04FA9E544D86CCDD0A"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SkylightFrameKonfigurator.Views;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Tekla.Structures.Dialog;
using Tekla.Structures.Dialog.UIControls;


namespace SkylightFrameKonfigurator.Views {
    
    
    /// <summary>
    /// WindowTyp2
    /// </summary>
    public partial class WindowTyp2 : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 28 "Views\WindowTyp2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button LoadSettings;
        
        #line default
        #line hidden
        
        
        #line 38 "Views\WindowTyp2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SaveSettings;
        
        #line default
        #line hidden
        
        
        #line 48 "Views\WindowTyp2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SaveSettingsAs;
        
        #line default
        #line hidden
        
        
        #line 58 "Views\WindowTyp2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ApplyTyp1Window1;
        
        #line default
        #line hidden
        
        
        #line 94 "Views\WindowTyp2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Cancel;
        
        #line default
        #line hidden
        
        
        #line 106 "Views\WindowTyp2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SavedSettingsName;
        
        #line default
        #line hidden
        
        
        #line 146 "Views\WindowTyp2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox FieldLengthTextBox;
        
        #line default
        #line hidden
        
        
        #line 148 "Views\WindowTyp2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox FrameWidthTextBox;
        
        #line default
        #line hidden
        
        
        #line 183 "Views\WindowTyp2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox UserDefinedCheckBox;
        
        #line default
        #line hidden
        
        
        #line 187 "Views\WindowTyp2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox AddStrutsCheckBox;
        
        #line default
        #line hidden
        
        
        #line 200 "Views\WindowTyp2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox LongFrameMaterialTextBox;
        
        #line default
        #line hidden
        
        
        #line 201 "Views\WindowTyp2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox LongFrameProfileComboBox;
        
        #line default
        #line hidden
        
        
        #line 210 "Views\WindowTyp2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox HeadFrameMaterialTextBox;
        
        #line default
        #line hidden
        
        
        #line 211 "Views\WindowTyp2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox HeadFrameProfileTextBox;
        
        #line default
        #line hidden
        
        
        #line 213 "Views\WindowTyp2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TopHookSizeLongFrameTextBox;
        
        #line default
        #line hidden
        
        
        #line 214 "Views\WindowTyp2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TopWidthLongFrameTextBox;
        
        #line default
        #line hidden
        
        
        #line 215 "Views\WindowTyp2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox HeightLongFrameTextBox;
        
        #line default
        #line hidden
        
        
        #line 216 "Views\WindowTyp2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox BottomWidthLongFrameTextBox;
        
        #line default
        #line hidden
        
        
        #line 217 "Views\WindowTyp2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox BottomHookSizeLongFrameTextBox;
        
        #line default
        #line hidden
        
        
        #line 218 "Views\WindowTyp2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TopHookSizeHeadFrameTextBox;
        
        #line default
        #line hidden
        
        
        #line 219 "Views\WindowTyp2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TopWidthHeadFrameTextBox;
        
        #line default
        #line hidden
        
        
        #line 220 "Views\WindowTyp2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox HeightHeadFrameTextBox;
        
        #line default
        #line hidden
        
        
        #line 221 "Views\WindowTyp2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox BottomAngleHeadFrameTextBox;
        
        #line default
        #line hidden
        
        
        #line 254 "Views\WindowTyp2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SizeBetweenBolts_Beam_LongFrameTextBox;
        
        #line default
        #line hidden
        
        
        #line 255 "Views\WindowTyp2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SizeBetweenBolt_EdgeLongFrameTextBox;
        
        #line default
        #line hidden
        
        
        #line 257 "Views\WindowTyp2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SizeBetweenEdgeLongFrame_EdgeBeamTextBox;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/SkylightFrameKonfigurator;component/views/windowtyp2.xaml", System.UriKind.Relative);
            
            #line 1 "Views\WindowTyp2.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 24 "Views\WindowTyp2.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Close_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.LoadSettings = ((System.Windows.Controls.Button)(target));
            return;
            case 3:
            this.SaveSettings = ((System.Windows.Controls.Button)(target));
            return;
            case 4:
            this.SaveSettingsAs = ((System.Windows.Controls.Button)(target));
            return;
            case 5:
            this.ApplyTyp1Window1 = ((System.Windows.Controls.Button)(target));
            return;
            case 6:
            this.Cancel = ((System.Windows.Controls.Button)(target));
            return;
            case 7:
            this.SavedSettingsName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.FieldLengthTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.FrameWidthTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.UserDefinedCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 11:
            this.AddStrutsCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 12:
            
            #line 188 "Views\WindowTyp2.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_StrutSettings_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.LongFrameMaterialTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 14:
            this.LongFrameProfileComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 15:
            this.HeadFrameMaterialTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 16:
            this.HeadFrameProfileTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 17:
            this.TopHookSizeLongFrameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 18:
            this.TopWidthLongFrameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 19:
            this.HeightLongFrameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 20:
            this.BottomWidthLongFrameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 21:
            this.BottomHookSizeLongFrameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 22:
            this.TopHookSizeHeadFrameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 23:
            this.TopWidthHeadFrameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 24:
            this.HeightHeadFrameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 25:
            this.BottomAngleHeadFrameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 26:
            this.SizeBetweenBolts_Beam_LongFrameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 27:
            this.SizeBetweenBolt_EdgeLongFrameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 28:
            this.SizeBetweenEdgeLongFrame_EdgeBeamTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

